// src/shell/sidebar/sidebarMenus.ts

"use client";

import {
    HiHome,
    HiUserGroup,
    HiOutlineClipboardList,
    HiOutlineHeart,
    HiOutlineCheckCircle,
    HiOutlineChartBar,
    HiOutlineCog,
} from "react-icons/hi";
import {FaPaw, FaSyringe} from "react-icons/fa";
import {MdLocalHospital, MdPets} from "react-icons/md";

import {
    HiOutlineDocumentText,
    HiOutlineCalendar,
    HiOutlinePaperClip,
    HiOutlineLightningBolt,
    HiOutlineLogout,
    HiOutlineClipboardCheck,
} from "react-icons/hi";
import {FaStethoscope, FaFlask} from "react-icons/fa";
import {MdBugReport} from "react-icons/md";
import {HiOutlineExclamationTriangle} from "react-icons/hi2";

import type {SidebarItemsConfig, SidebarMenuConfig} from "./sidebarContext";

/* =========================================================
   GLOBAL MENU
   ========================================================= */

const globalSidebarMenuItems: SidebarItemsConfig[] = [
    {
        itemId: "globalSidebar_inicio",
        itemLabel: "Inicio",
        itemIcon: HiHome,
        itemAction: {type: "go_to_component", path: "/inicio"},
        itemPath: "/inicio",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_gestion_datos",
        itemLabel: "Gestión de Datos",
        itemIcon: FaPaw,
        itemAction: {
            type: "go_to_section",
            menuId: "gestion_datos",
        },
        itemPath: "/gestion_datos",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_paciente",
        itemLabel: "Paciente",
        itemIcon: MdPets,
        itemAction: {
            type: "go_to_section",
            menuId: "paciente",
        },
        itemPath: "/paciente",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_clientes",
        itemLabel: "Clientes",
        itemIcon: HiUserGroup,
        itemAction: {
            type: "go_to_section",
            menuId: "clientes",
        },
        itemPath: "/clientes",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_consultas",
        itemLabel: "Consultas",
        itemIcon: HiOutlineClipboardList,
        itemAction: {
            type: "go_to_section",
            menuId: "consultas",
        },
        itemPath: "/consultas",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_vacunas",
        itemLabel: "Vacunas",
        itemIcon: FaSyringe,
        itemAction: {
            type: "go_to_section",
            menuId: "vacunas",
        },
        itemPath: "/vacunas",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_enfermedades",
        itemLabel: "Enfermedades",
        itemIcon: MdBugReport,
        itemAction: {
            type: "go_to_section",
            menuId: "enfermedades",
        },
        itemPath: "/enfermedades",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_hospitalizacion",
        itemLabel: "Hospitalización",
        itemIcon: MdLocalHospital,
        itemAction: {
            type: "go_to_section",
            menuId: "hospitalizacion",
        },
        itemPath: "/hospitalizacion",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_campañas",
        itemLabel: "Campañas",
        itemIcon: HiOutlineClipboardCheck,
        itemAction: {
            type: "go_to_section",
            menuId: "campaña",
        },
        itemPath: "/campañas",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_tareas",
        itemLabel: "Tareas",
        itemIcon: HiOutlineClipboardCheck,
        itemAction: {
            type: "go_to_section",
            menuId: "tareas",
        },
        itemPath: "/tareas",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_analiticas",
        itemLabel: "Reportes",
        itemIcon: HiOutlineChartBar,
        itemAction: {
            type: "go_to_section",
            menuId: "analiticas",
        },
        itemPath: "/analiticas",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "globalSidebar_configuracion",
        itemLabel: "Configuración",
        itemIcon: HiOutlineCog,
        itemAction: {
            type: "go_to_section",
            menuId: "configuracion",
        },
        itemPath: "/configuracion",
        itemDisabled: false,
        itemTextColor: "text-slate-400",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: true,
        itemBottomBorder: false,
        itemTooltip: "",
    },
];

export const globalSidebarMenu: SidebarMenuConfig = {
    menuId: "inicio",
    label: "Menú Principal",
    items: globalSidebarMenuItems,
    defaultPath: "/inicio",
};

/* =========================================================
   DATA MANAGEMENT MENU
   ========================================================= */

const dataManagementMenuItems: SidebarItemsConfig[] = [
    {
        itemId: "gestion_datos",
        itemLabel: "Inicio: Gestión de Datos",
        itemIcon: HiOutlineDocumentText,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos",
        },
        itemPath: "/gestion_datos",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "dataManagement",
    },
    {
        itemId: "gestion_datos_datos_paciente",
        itemLabel: "Datos del paciente",
        itemIcon: HiOutlineDocumentText,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/datos_paciente",
        },
        itemPath: "/gestion_datos/datos_paciente",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "patientData",
    },
    {
        itemId: "gestion_datos_contactos_del_centro",
        itemLabel: "Contactos del Centro",
        itemIcon: HiUserGroup,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/contactos_del_centro",
        },
        itemPath: "/gestion_datos/contactos_del_centro",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "contactsData",
    },
    {
        itemId: "gestion_datos_registrar_nuevo_paciente",
        itemLabel: "Registrar Nuevo Paciente",
        itemIcon: HiOutlineClipboardList,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/registrar_nuevo_paciente",
        },
        itemPath: "/gestion_datos/registrar_nuevo_paciente",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_pacientes_activos",
        itemLabel: "Pacientes Activos",
        itemIcon: HiOutlineCheckCircle,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/pacientes_activos",
        },
        itemPath: "/gestion_datos/pacientes_activos",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_pacientes_hospitalizados",
        itemLabel: "Hospitalizados",
        itemIcon: MdLocalHospital,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/pacientes_hospitalizados",
        },
        itemPath: "/gestion_datos/pacientes_hospitalizados",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_seguimientos_pendientes",
        itemLabel: "Seguimientos Pendientes",
        itemIcon: HiOutlineLightningBolt,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/seguimientos_pendientes",
        },
        itemPath: "/gestion_datos/seguimientos_pendientes",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_alertas_clinicas",
        itemLabel: "Alertas Clínicas",
        itemIcon: HiOutlineHeart,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/alertas_clinicas",
        },
        itemPath: "/gestion_datos/alertas_clinicas",
        itemDisabled: false,
        itemTextColor: "text-amber-400",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_archivos_clinicos",
        itemLabel: "Archivos Clínicos",
        itemIcon: HiOutlinePaperClip,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/archivos_clinicos",
        },
        itemPath: "/gestion_datos/archivos_clinicos",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_historia",
        itemLabel: "Históricos",
        itemIcon: HiOutlineDocumentText,
        itemAction: {
            type: "go_to_component",
            path: "/gestion_datos/historia",
        },
        itemPath: "/gestion_datos/historia",
        itemDisabled: false,
        itemTextColor: "text-slate-400",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_cerrar",
        itemLabel: "Cerrar",
        itemIcon: HiOutlineLogout,
        itemAction: {
            type: "go_to_section",
            menuId: "inicio",
        },
        itemPath: "/inicio",
        itemDisabled: false,
        itemTextColor: "text-slate-400",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: true,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "gestion_datos_configuracion",
        itemLabel: "Configuración",
        itemIcon: HiOutlineCog,
        itemAction: {type: "go_to_component", path: "/settings"},
        itemPath: "/settings",
        itemDisabled: false,
        itemTextColor: "text-slate-400",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: true,
        itemBottomBorder: false,
        itemTooltip: "",
    },
];

export const dataManagementSidebarMenu: SidebarMenuConfig = {
    menuId: "gestion_datos",
    label: "Gestión de Datos",
    items: dataManagementMenuItems,
    defaultPath: "/gestion_datos",
};

/* =========================================================
   PATIENT MENU
   ========================================================= */

const patientMenuItems: SidebarItemsConfig[] = [
    {
        itemId: "paciente",
        itemLabel: "Inicio: Paciente",
        itemIcon: HiOutlineDocumentText,
        itemAction: {type: "go_to_component", path: "/paciente"},
        itemPath: "/paciente",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "fichaPaciente",
    },
    {
        itemId: "paciente_datos_paciente",
        itemLabel: "Datos del Paciente",
        itemIcon: HiOutlineDocumentText,
        itemAction: {type: "go_to_component", path: "/paciente/datos_paciente"},
        itemPath: "/paciente/datos_paciente",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "fichaPaciente",
    },
    {
        itemId: "paciente_situacion_clinica",
        itemLabel: "Situación Clínica",
        itemIcon: HiOutlineDocumentText,
        itemAction: {
            type: "go_to_component",
            path: "/paciente/situacion_clinica",
        },
        itemPath: "/paciente/situacion_clinica",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "situacionClinica",
    },
    {
        itemId: "paciente_historia_clinica",
        itemLabel: "Historia Clínica",
        itemIcon: FaStethoscope,
        itemAction: {
            type: "go_to_component",
            path: "/paciente/historia_clinica",
        },
        itemPath: "/paciente/historia_clinica",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_consultas",
        itemLabel: "Consultas",
        itemIcon: FaSyringe,
        itemAction: {type: "go_to_component", path: "/paciente/consultas"},
        itemPath: "/paciente/consultas",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_enfermedades_y_condiciones",
        itemLabel: "Enfermedades y Condiciones",
        itemIcon: MdBugReport,
        itemAction: {
            type: "go_to_component",
            path: "/paciente/enfermedades_y_condiciones",
        },
        itemPath: "/paciente/enfermedades_y_condiciones",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "enfermedadesYCondiciones",
    },
    {
        itemId: "paciente_procedimientos_y_estudios",
        itemLabel: "Procedimientos y Estudios",
        itemIcon: FaFlask,
        itemAction: {
            type: "go_to_component",
            path: "/paciente/procedimientos_y_estudios",
        },
        itemPath: "/paciente/procedimientos_y_estudios",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "procedimientosYEstudios",
    },
    {
        itemId: "paciente_vacunacion",
        itemLabel: "Vacunación",
        itemIcon: HiOutlineCalendar,
        itemAction: {type: "go_to_component", path: "/paciente/vacunacion"},
        itemPath: "/paciente/vacunacion",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_hospitalization_and_observation",
        itemLabel: "Hospitalización / Observación",
        itemIcon: HiOutlineExclamationTriangle,
        itemAction: {
            type: "go_to_component",
            path: "/paciente/hospitalizationAndObservation",
        },
        itemPath: "/paciente/hospitalizationAndObservation",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_estado_critico",
        itemLabel: "Estado Crítico",
        itemIcon: HiOutlinePaperClip,
        itemAction: {type: "go_to_component", path: "/paciente/estado_critico"},
        itemPath: "/paciente/estado_critico",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_seguimientos_y_recordatorios",
        itemLabel: "Seguimiento y Recordatorios",
        itemIcon: HiOutlineLightningBolt,
        itemAction: {
            type: "go_to_component",
            path: "/paciente/seguimientos_y_recordatorios",
        },
        itemPath: "/paciente/seguimientos_y_recordatorios",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_cerrar",
        itemLabel: "Cerrar",
        itemIcon: HiOutlineLogout,
        itemAction: {
            type: "go_to_section",
            menuId: "inicio",
        },
        itemPath: "/inicio",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: true,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "paciente_configuracion",
        itemLabel: "Configuración",
        itemIcon: HiOutlineCog,
        itemAction: {type: "go_to_component", path: "/paciente/configuracion"},
        itemPath: "/paciente/configuracion",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: true,
        itemBottomBorder: false,
        itemTooltip: "",
    },
];

export const patientSidebarMenu: SidebarMenuConfig = {
    menuId: "paciente",
    label: "Paciente",
    items: patientMenuItems,
    defaultPath: "/paciente",
};

/* =========================================================
   ADMIN MENU
   ========================================================= */

const adminMenuItems: SidebarItemsConfig[] = [
    {
        itemId: "admin_inicio",
        itemLabel: "Inicio",
        itemIcon: HiHome,
        itemAction: {type: "go_to_component", path: "/inicio"},
        itemPath: "/inicio",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
    {
        itemId: "admin_settings",
        itemLabel: "Configuración",
        itemIcon: HiOutlineCog,
        itemAction: {type: "go_to_component", path: "/settings"},
        itemPath: "/settings",
        itemDisabled: false,
        itemTextColor: "text-slate-300",
        itemBold: false,
        itemUnderline: false,
        itemTopBorder: false,
        itemBottomBorder: false,
        itemTooltip: "",
    },
];

export const adminSidebarMenu: SidebarMenuConfig = {
    menuId: "admin",
    label: "Administración",
    items: adminMenuItems,
    defaultPath: "/inicio",
};

export const sidebarMenus: SidebarMenuConfig[] = [
    globalSidebarMenu,
    adminSidebarMenu,
    patientSidebarMenu,
    dataManagementSidebarMenu,
];
