// src/constants/AppConstants.ts

export const SET_GLOBAL_MESSAGE = "SET_GLOBAL_MESSAGE";
export const CLEAR_GLOBAL_MESSAGE = "CLEAR_GLOBAL_MESSAGE";

export const SET_NEXT_PATH = "SET_NEXT_PATH";
export const CLEAR_NEXT_PATH = "CLEAR_NEXT_PATH";
export const SET_GLOBAL_MESSAGE_TYPE = "SET_GLOBAL_MESSAGE_TYPE";
export const CLEAR_GLOBAL_MESSAGE_TYPE = "CLEAR_GLOBAL_MESSAGE_TYPE";

export const LOAD_SPECIES_AND_BREEDS = "LOAD_SPECIES_AND_BREEDS";
export const SET_SPECIES_AND_BREEDS = "SET_SPECIES_AND_BREEDS";
export const CLEAR_SPECIES_AND_BREEDS = "CLEAR_SPECIES_AND_BREEDS";
export const SET_SPECIES_AND_BREEDS_ERROR = "";
